/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.assignment.gui;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import com.assignment.data.Staff;
import com.assignment.data.Staff.Occupation;
import com.assignment.service.ServiceException;
import com.assignment.service.ServiceFactory;
import com.assignment.service.StaffService;
import com.formdev.flatlaf.ui.FlatRoundBorder;

/**
 *
 * @author meher
 */
public class StaffPanel extends javax.swing.JPanel {
    Staff staff;
    DrawMode drawMode;

    /**
     * Creates new form StaffPanel
     */
    @SuppressWarnings("incomplete-switch")
    public StaffPanel(Staff staff, DrawMode drawMode) {
        initComponents();
        this.staff = staff;
        this.drawMode = drawMode;
        switch (drawMode) {
            case UPDATE:
                button.setText("Update");
                setAllText(staff);
                setAllEditable();
                setAllFocusable();
                loadOccupation();
                username.setEditable(false);
                break;
            
            case CREATE:
                button.setText("Add");
                setAllEditable();
                setAllFocusable();
                occupation.removeAllItems();
                removeButton.setVisible(false);
                loadOccupation();
                break;
        }
    }

    private void setAllText(Staff staff) {
        username.setText(staff.getUsername());
        firstName.setText(staff.getFirstName());
        lastName.setText(staff.getLastName());
        cnic.setText(Long.toString(staff.getCnic()));
        address.setText(staff.getAddress());
        contact.setText(staff.getContact());
        email.setText(staff.getEmail());
        occupation.removeAllItems();
        occupation.addItem(staff.getOccupation().toString());
    }

    private void setAllEditable() {
        username.setEditable(true);
        firstName.setEditable(true);
        lastName.setEditable(true);
        cnic.setEditable(true);
        address.setEditable(true);
        contact.setEditable(true);
        email.setEditable(true);
        occupation.setEnabled(true);
    }

    private void setAllFocusable() {
        username.setFocusable(true);
        firstName.setFocusable(true);
        lastName.setFocusable(true);
        cnic.setFocusable(true);
        address.setFocusable(true);
        contact.setFocusable(true);
        email.setFocusable(true);
        occupation.setEnabled(true);
    }

    private void loadOccupation() {
        //occupation.removeAllItems();
        for (Occupation o : Occupation.values()) {
            if (occupation.getSelectedItem() != o.toString()) {
                occupation.addItem(o.toString());
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        cnic = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        occupation = new javax.swing.JComboBox<>();
        contact = new javax.swing.JTextField();
        button = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();

        setBorder(new FlatRoundBorder());

        firstName.setEditable(false);
        firstName.setToolTipText("");
        firstName.setBorder(new FlatRoundBorder());
        firstName.setFocusable(false);
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });

        jLabel5.setText("Address");

        jLabel3.setText("CNIC");

        address.setEditable(false);
        address.setBorder(new FlatRoundBorder());
        address.setFocusable(false);

        jLabel2.setText("Last Name");

        email.setEditable(false);
        email.setBorder(new FlatRoundBorder());
        email.setFocusable(false);

        cnic.setEditable(false);
        cnic.setBorder(new FlatRoundBorder());
        cnic.setFocusable(false);

        lastName.setEditable(false);
        lastName.setBorder(new FlatRoundBorder());
        lastName.setFocusable(false);

        jLabel6.setText("Contact");

        jLabel1.setText("First Name");

        jLabel4.setText("E-mail");

        username.setEditable(false);
        username.setToolTipText("");
        username.setBorder(new FlatRoundBorder());
        username.setFocusable(false);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jLabel8.setText("Username");

        jLabel7.setText("Occupation");

        occupation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        occupation.setEnabled(false);
        occupation.setFocusable(false);

        contact.setEditable(false);
        contact.setBorder(new FlatRoundBorder());
        contact.setFocusable(false);

        button.setBackground(new java.awt.Color(153, 153, 0));
        button.setText("Update");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        removeButton.setBackground(new java.awt.Color(204, 0, 51));
        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeButton)
                        .addGap(18, 18, 18)
                        .addComponent(button))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstName, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(lastName)
                            .addComponent(cnic)
                            .addComponent(email)
                            .addComponent(address)
                            .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(occupation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(contact))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(occupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button)
                    .addComponent(removeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        
    }//GEN-LAST:event_firstNameActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        
    }//GEN-LAST:event_usernameActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // DatabaseConnectionService db = new DatabaseConnectionServiceImpl();
        // ServiceFactory serviceFactory = new ServiceFactory();
        // StaffService staffService = serviceFactory.getStaffService();
        JOptionPane.showMessageDialog(null, "Functionality not implemented yet");
    }//GEN-LAST:event_removeButtonActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
    ServiceFactory serviceFactory = new ServiceFactory();
    StaffService staffService = serviceFactory.getStaffService();
    switch (this.drawMode) {
        case CREATE:
            Staff staff = new Staff(0, username.getText(), firstName.getText(), lastName.getText(), Long.parseLong(cnic.getText()), address.getText(), contact.getText(), email.getText(), Occupation.valueOf(occupation.getSelectedItem().toString()));
            try {
                staffService.registerStaff(staff);
                try {
                    java.awt.Window window = SwingUtilities.getWindowAncestor(this);
                    if (window instanceof MainWindow) {
                        ((MainWindow) window).refreshStaff();
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    JOptionPane.showMessageDialog(null, "Staff registered successfully");
                }
            } catch (ServiceException e) {
                e.printStackTrace();
            }
            break;

        case UPDATE:
            Staff updatedStaff = new Staff(this.staff.getId(), username.getText(), firstName.getText(), lastName.getText(), Long.parseLong(cnic.getText()), address.getText(), contact.getText(), email.getText(), Occupation.valueOf(occupation.getSelectedItem().toString()));
            if (updatedStaff.equals(this.staff)) {
                JOptionPane.showMessageDialog(null, "No changes were made");
            } else {
                try {
                    staffService.updateStaff(updatedStaff);
                    java.awt.Window window = SwingUtilities.getWindowAncestor(this);
                    if (window instanceof MainWindow) {
                        ((MainWindow) window).refreshStaff();
                    }
                    JOptionPane.showMessageDialog(null, "Staff updated successfully");
                } catch (ServiceException e) {
                    e.printStackTrace();
                }
            }
            break;

        default:
            break;
    }
}//GEN-LAST:event_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton button;
    private javax.swing.JTextField cnic;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField lastName;
    private javax.swing.JComboBox<String> occupation;
    private javax.swing.JButton removeButton;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
