/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.assignment.gui;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import com.assignment.data.User;
import com.assignment.service.ServiceFactory;
import com.assignment.service.UserService;
import com.formdev.flatlaf.ui.FlatRoundBorder;

/**
 *
 * @author meher
 */
public class UserPanel extends javax.swing.JPanel {
    private User user;
    private DrawMode drawMode;

    /**
     * Creates new form UserPanel
     */
    @SuppressWarnings("incomplete-switch")
    public UserPanel(User user, DrawMode drawMode) {
        this.user = user;
        this.drawMode = drawMode;
        initComponents();
        switch (drawMode) {
            case ADMIN:
            case LIBRARIAN:
            case MANAGER:
            case UPDATE:
                button.setText("Update");
                setAllText();
                passsword.setVisible(false);
                passwordLable.setVisible(false);
                setAllEditable(true);
                setAllFocusable(true);
                username.setEditable(false);
                break;

            case CREATE:
                button.setText("Add");
                setAllEditable(true);
                setAllFocusable(true);
                removeButton.setVisible(false);
                break;
        }
    }

    private void setAllText() {
        username.setText(user.getUsername());
        firstName.setText(user.getFirstName());
        lastName.setText(user.getLastName());
        cnic.setText(Long.toString(user.getCnic()));
        address.setText(user.getAddress());
        contact.setText(user.getContact());
        email.setText(user.getEmail());
        borrowings.setText(Integer.toString(user.getBorrowings()));
        bookBorrowLimit.setText(Integer.toString(user.getBookBorrowLimit()));
        magazineBorrowLimit.setText(Integer.toString(user.getMagazineBorrowLimit()));
    }

    private void setAllEditable(boolean choise) {
        username.setEditable(choise);
        firstName.setEditable(choise);
        lastName.setEditable(choise);
        cnic.setEditable(choise);
        address.setEditable(choise);
        contact.setEditable(choise);
        email.setEditable(choise);
        borrowings.setEditable(choise);
        magazineBorrowLimit.setEditable(choise);
        bookBorrowLimit.setEditable(choise);
    }

    private void setAllFocusable(boolean choise) {
        username.setFocusable(choise);
        firstName.setFocusable(choise);
        lastName.setFocusable(choise);
        cnic.setFocusable(choise);
        address.setFocusable(choise);
        contact.setFocusable(choise);
        email.setFocusable(choise);
        borrowings.setFocusable(choise);
        magazineBorrowLimit.setFocusable(choise);
        bookBorrowLimit.setFocusable(choise);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cnic = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        borrowings = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        magazineBorrowLimit = new javax.swing.JTextField();
        bookBorrowLimit = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        button = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        passsword = new javax.swing.JTextField();
        passwordLable = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();

        setBorder(new FlatRoundBorder());

        cnic.setEditable(false);
        cnic.setBorder(new FlatRoundBorder());
        cnic.setFocusable(false);

        email.setEditable(false);
        email.setBorder(new FlatRoundBorder());
        email.setFocusable(false);

        jLabel2.setText("Last Name");

        borrowings.setEditable(false);
        borrowings.setBorder(new FlatRoundBorder());
        borrowings.setFocusable(false);

        address.setEditable(false);
        address.setBorder(new FlatRoundBorder());
        address.setFocusable(false);

        jLabel3.setText("CNIC");

        jLabel8.setText("Username");

        jLabel5.setText("Address");

        firstName.setEditable(false);
        firstName.setToolTipText("");
        firstName.setBorder(new FlatRoundBorder());
        firstName.setFocusable(false);
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });

        username.setEditable(false);
        username.setToolTipText("");
        username.setBorder(new FlatRoundBorder());
        username.setFocusable(false);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jLabel4.setText("E-mail");

        jLabel1.setText("First Name");

        jLabel6.setText("Borrowings");

        lastName.setEditable(false);
        lastName.setBorder(new FlatRoundBorder());
        lastName.setFocusable(false);

        magazineBorrowLimit.setEditable(false);
        magazineBorrowLimit.setBorder(new FlatRoundBorder());
        magazineBorrowLimit.setFocusable(false);

        bookBorrowLimit.setEditable(false);
        bookBorrowLimit.setBorder(new FlatRoundBorder());
        bookBorrowLimit.setFocusable(false);

        contact.setEditable(false);
        contact.setBorder(new FlatRoundBorder());
        contact.setFocusable(false);

        jLabel9.setText("Book Limit");

        jLabel10.setText("Magazine Limit");

        jLabel11.setText("Contact");

        button.setBackground(new java.awt.Color(153, 153, 0));
        button.setText("Update");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        removeButton.setBackground(new java.awt.Color(204, 0, 51));
        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        passsword.setToolTipText("");
        passsword.setBorder(new FlatRoundBorder());
        passsword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passswordActionPerformed(evt);
            }
        });

        passwordLable.setText("Password");

        userLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLabel.setText("User");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeButton)
                        .addGap(18, 18, 18)
                        .addComponent(button)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(passwordLable))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passsword, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(contact)
                            .addComponent(firstName, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(lastName)
                            .addComponent(cnic)
                            .addComponent(email)
                            .addComponent(address)
                            .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(borrowings)
                            .addComponent(magazineBorrowLimit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bookBorrowLimit))))
                .addGap(22, 22, 22))
            .addComponent(userLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passsword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(borrowings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookBorrowLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(magazineBorrowLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button)
                    .addComponent(removeButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // nothing to do here
    }//GEN-LAST:event_firstNameActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // nothing to do here
    }//GEN-LAST:event_usernameActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        JOptionPane.showMessageDialog(null, "Functionality not implemented yet!");
    }//GEN-LAST:event_removeButtonActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        ServiceFactory serviceFactory = new ServiceFactory();
        UserService userService = serviceFactory.getUserService();
        switch (this.drawMode) {
            case CREATE:
                User newUser = new User(0, username.getText(), firstName.getText(), lastName.getText(), Long.parseLong(cnic.getText()), address.getText(), contact.getText(), email.getText(), Integer.parseInt(borrowings.getText()), Integer.parseInt(bookBorrowLimit.getText()), Integer.parseInt(magazineBorrowLimit.getText()));
                try {
                    userService.registerUser(newUser, passsword.getText());
                    try {
                        ((MainWindow) SwingUtilities.getWindowAncestor((JDialog) SwingUtilities.getWindowAncestor(this))).refreshStaff();
                    } catch (Exception e) {
                        e.printStackTrace();
                    } finally {
                        JOptionPane.showMessageDialog(this, "User registered successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                        ((JDialog) SwingUtilities.getWindowAncestor(this)).dispose();
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
                break;

            case UPDATE:
                User updatedUser = new User(this.user.getId(), this.user.getUsername(), firstName.getText(), lastName.getText(), Long.parseLong(cnic.getText()), address.getText(), contact.getText(), email.getText(), Integer.parseInt(borrowings.getText()), Integer.parseInt(bookBorrowLimit.getText()), Integer.parseInt(magazineBorrowLimit.getText()));
                if (updatedUser.equals(this.user)) {
                    JOptionPane.showMessageDialog(this, "No changer were made", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    try {
                        userService.updateUser(updatedUser);
                        try {
                            ((MainWindow) SwingUtilities.getWindowAncestor(this)).refreshStaff();
                        } catch (Exception e) {
                            e.printStackTrace();
                        } finally {
                            JOptionPane.showMessageDialog(this, "User updated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
                break;
        
            default:
                break;
        }
    }//GEN-LAST:event_buttonActionPerformed

    private void passswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passswordActionPerformed
        // nothing to do here
    }//GEN-LAST:event_passswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField bookBorrowLimit;
    private javax.swing.JTextField borrowings;
    private javax.swing.JButton button;
    private javax.swing.JTextField cnic;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField magazineBorrowLimit;
    private javax.swing.JTextField passsword;
    private javax.swing.JLabel passwordLable;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
